import { AlertTriangle, ArrowRight, Building2, CircleDollarSign, Clock3, Gavel, Users, UserRoundCheck } from "lucide-react";
import { AdminCompanyControls } from "@/components/admin-company-controls";
import { CompanyAvatar } from "@/components/company-avatar";
import { CsvExport } from "@/components/csv-export";
import { StatusBadge } from "@/components/status-badge";
import { demandCategory, formatDateTime } from "@/lib/business";
import { requireProfile } from "@/lib/auth";
import { getAdminData } from "@/lib/data";

export default async function AdminPage() {
  await requireProfile(["admin", "viewer"]);
  const { companies, applications } = await getAdminData();
  const live = companies.find((company) => ["open", "paused", "bid_increase_pending"].includes(company.status));
  const active = applications.filter((application) => ["active_bid", "confirmed", "confirmation_required"].includes(application.status));
  const applicantRows = active.map((application) => ({ registration_number: application.profile?.registration_number ?? "", student: application.profile?.full_name ?? "", email: application.profile?.email ?? "", company: application.company?.name ?? "", accepted_bid: application.accepted_bid, status: application.status }));

  return <div className="dashboard-page">
    <div className="page-title-row"><div><span className="page-kicker">BIDDING CONTROL ROOM</span><h1>Live session dashboard</h1><p>Monitor demand, guide bid rounds, and finalize with confidence.</p></div><CsvExport filename="active-applicants" rows={applicantRows} label="Export applicants" /></div>
    <section className="metric-grid"><article className="metric-card emphasis"><span className="metric-icon"><Building2 /></span><div><small>LIVE COMPANY</small><strong className="metric-word">{live?.name ?? "None"}</strong><p>{live ? `Closes ${formatDateTime(live.closes_at)}` : "No active session"}</p></div></article><article className="metric-card"><span className="metric-icon blue"><Users /></span><div><small>ACTIVE APPLICANTS</small><strong>{live?.applicant_count ?? 0}</strong><p>{live?.cv_requirement ?? 0} CV slots available</p></div></article><article className="metric-card"><span className="metric-icon amber"><Clock3 /></span><div><small>PENDING RESPONSES</small><strong>{live?.pending_count ?? 0}</strong><p>After latest bid change</p></div></article><article className="metric-card"><span className="metric-icon purple"><CircleDollarSign /></span><div><small>CURRENT BID</small><strong>{live?.current_bid ?? 0}</strong><p>points per applicant</p></div></article></section>
    {live ? <>
      {live.applicant_count > live.cv_requirement && <div className="warning-banner"><AlertTriangle /><span><strong>Oversubscription needs attention</strong>{live.applicant_count - live.cv_requirement} more applicants than available CV slots. Increase the bid or request more capacity.</span></div>}
      <section className="admin-live-card"><div className="admin-live-head"><div className="admin-live-company"><CompanyAvatar name={live.name} logoUrl={live.logo_url} large /><div><span className="live-label"><span className="live-dot" /> LIVE SESSION</span><h2>{live.name}</h2><p>{live.industry} · {live.location}</p></div></div><StatusBadge status={live.status} /></div><div className="admin-live-stats"><div><small>APPLICANTS</small><strong>{live.applicant_count}</strong><span>for {live.cv_requirement} slots</span></div><div><small>DEMAND RATIO</small><strong className={live.demand_ratio > 1 ? "danger-text" : ""}>{live.demand_ratio.toFixed(2)}×</strong><span>{demandCategory(live.demand_ratio)}</span></div><div><small>CONFIRMED</small><strong>{live.confirmed_count}</strong><span>{live.pending_count} pending</span></div><div><small>CURRENT BID</small><strong>{live.current_bid}</strong><span>+{live.bid_increment} standard step</span></div></div><div className="demand-track large"><span className={live.demand_ratio > 1 ? "over" : ""} style={{ width: `${Math.min(100, live.demand_ratio * 100)}%` }} /></div><AdminCompanyControls company={live} /></section>
    </> : <section className="no-live-banner admin"><Gavel /><div><strong>No bidding session is live</strong><span>Open an upcoming company from the company management page.</span></div><a href="/admin/companies">Manage companies <ArrowRight size={16} /></a></section>}
    <section className="dashboard-section"><div className="section-title-row"><div><span className="page-kicker">LIVE APPLICANT FEED</span><h2>Applicant responses</h2></div><span className="realtime-state connected"><span className="live-dot" /> Updates automatically</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Student</th><th>Company</th><th>Bid</th><th>Applied</th><th>Status</th></tr></thead><tbody>{active.slice(0, 12).map((application) => <tr key={application.id}><td><div className="table-person"><span className="table-user-icon"><UserRoundCheck /></span><span><strong>{application.profile?.full_name}</strong><small>{application.profile?.registration_number}</small></span></div></td><td>{application.company?.name}</td><td><strong>{application.accepted_bid} pts</strong></td><td>{formatDateTime(application.applied_at)}</td><td><StatusBadge status={application.status} /></td></tr>)}</tbody></table>{!active.length && <div className="empty-list">No active applicants yet.</div>}</div></section>
  </div>;
}
